# Generated by Django 5.0.6 on 2024-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pres', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('psal', models.FloatField(blank=True, null=True)),
                ('dox1', models.FloatField(blank=True, null=True)),
                ('dox2', models.FloatField(blank=True, null=True)),
                ('cphl', models.FloatField(blank=True, null=True)),
                ('cdom', models.FloatField(blank=True, null=True)),
                ('cndc', models.FloatField(blank=True, null=True)),
                ('vbsc', models.FloatField(blank=True, null=True)),
                ('head', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
    ]
