
[connections.postgresql]
dialect = "postgresql"
host='ep-summer-leaf-a1dja8ne.ap-southeast-1.aws.neon.tech'
port = "5432"
database = "Datacollect"
username = "Datacollect_owner"
password = "EgGTwtQ8f3Ik"




